### ISSUE TITLE
undefined method when reinsertir battler

### ISSUE THREAD

**Issue by vientodelbosque** [Archeia/YEARepo#9]
When removing an actor, and then re-inserting in the party a few turns later it throws a undefined method (move). I think this can be solved calling the inicialization of the script when adding the actor to the party, but i don't know how to achieve it

**Comment by Archeia** [comment]
Hi. This is what we have placed in the Yanfly Blog :)
I also don't understand the report as it doesn't also state which script does it.

List of scripts used. This is important! If you use Victor’s scripts, then it’s a given Yanfly scripts won’t work due to low compatibility.

Description of the bug. Make sure to note HOW it happens and try to emulate it as much as possible.

Did you test it in a fresh new project? If no, then try at a new project first.

Did you load a save and encountered the bug there? If yes, then start a new game and see if the problem persists.

Did you check Yanfly’s Core first for bug fixes list? Is the bug mentioned there? If yes, then grab that script.

Did you read the features of the script first before assuming it’s not working like what you thought it would? If no, then read.

Did you try putting the script above/below other/certain scripts first? Give it a try, it might just fix it.
Give us a demo if possible. No need for the entire game, but just the area where it bugs out.
